# Generated by Django 3.0.7 on 2020-09-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
