# Generated by Django 3.0.7 on 2020-11-15 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('summary', models.CharField(max_length=128)),
                ('inc_type', models.CharField(choices=[('Salary', 'Salary'), ('Others', 'Others')], max_length=56)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('summary', models.CharField(max_length=128)),
                ('exp_type', models.CharField(choices=[('Food', 'Food'), ('Rent', 'Rent'), ('Entertainment', 'Entertainment'), ('Business', 'Business'), ('Travel', 'Travel'), ('Misc', 'Misc')], max_length=56)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
