# Generated by Django 3.0.7 on 2020-11-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_expense_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='income',
            name='amt',
            field=models.IntegerField(default=0),
        ),
    ]
