# Generated by Django 3.0.7 on 2020-11-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_auto_20201115_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='exp_type',
            new_name='t_type',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='inc_type',
            new_name='t_type',
        ),
    ]
